version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: petinder_postgres
    restart: always
    environment:
      POSTGRES_USER: petinder
      POSTGRES_PASSWORD: petinder123
      POSTGRES_DB: petinderdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
