spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/petmatchdb
    username: petmatch
    password: petmatch123
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      indent_output: true

server:
  port: 8080

jwt:
  secret: 12345678901234567890123456789012
  expiration: 86400000

logging:
  level:
    root: INFO
    com.petmatch: DEBUG

# Configuraci√≥n de Cloudinary
cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}
