spring:
  main:
    banner-mode: "console"
  datasource:
    url: jdbc:postgresql://localhost:5432/petmatchdb
    username: petmatch
    password: petmatch123
  jpa:
    open-in-view: false # Desactiva la advertencia y es una mejor práctica
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        # No es necesario especificar el dialecto, Hibernate lo detecta
  jackson:
    serialization:
      indent_output: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

logging:
  level:
    root: INFO # Nivel por defecto INFO, más limpio que WARN para el arranque
    com.petmatch: DEBUG
    org.springframework.web: INFO
    org.hibernate: ERROR # Oculta las advertencias y logs de DEBUG de Hibernate

# Configuración de Cloudinary
cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}
